### ISSUE TITLE
Error using the AvTraj code example

### ISSUE THREAD

**Issue by samuelhaysom** [Fluorescence-Tools/avtraj#7]
Hello,

I am encountering the following error when using the code example given on the AvTraj front page:

Traceback (most recent call last):
  File "Avtraj_example.py", line 33, in <module>
    av_traj_donor[0].save_xyz('test.xyz')
  File "/anaconda3/lib/python3.7/site-packages/avtraj/trajectory.py", line 226, in __getitem__
    **parameters
  File "/anaconda3/lib/python3.7/site-packages/avtraj/av.py", line 642, in __init__
    self.update_av()
  File "/anaconda3/lib/python3.7/site-packages/avtraj/av.py", line 538, in update_av
    self._points = av_all.points().T
AttributeError: 'LabelLib.Grid3D' object has no attribute 'points'

**Comment by tpeulen** [comment]
That issue should be gone in newer LabelLib versions.
